# Generated by Django 5.2.4 on 2025-07-27 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, default='default-slug', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
